apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  destination:
    namespace: default
    name: kind
  project: default
  source:
    path: apps
    repoURL: https://github.com/morey-tech/argo-cd-kyverno.git
    targetRevision: main