apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
spec:
  destination:
    name: kind
    namespace: kyverno
  source:
    repoURL: 'https://kyverno.github.io/kyverno/'
    chart: kyverno
    targetRevision: 2.7.0
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true