apiVersion: v1
kind: Pod
metadata:
  name: nginx-fail
  namespace: dev
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pass
  namespace: dev
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"