name: Run unit tests
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:
    types: rebuild
# repository_dispatch:

# Jobs will run in parallel
jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment: dev
    # Steps run synchronously (one after the other)
    steps:
      # Retrieve the codebase on the ubuntu machine.
      # if the codebase isn't required, this step can be skipped.
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/cache@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'npm'
          dependency-path: subdir/package-lock.json
      -  run: npm ci
      -  run: npm install
      -  run: npm run build
