name: Run unit tests
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:
    types: rebuild
# repository_dispatch:

# Jobs will run in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    # Steps run synchronously (one after the other)
    steps:
      # Retrieve the codebase on the ubuntu machine.
      # if the codebase isn't required, this step can be skipped.
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - name: Run unit tests
        run: npm test
      - name: try and build
        run: npm run build
