name: Update configuration files

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  call-update-configuration-files:
    name: Update configuration files
    uses: actions/reusable-workflows/.github/workflows/update-config-files.yml@main
